### ISSUE TITLE
Validation doesn't work

### ISSUE THREAD

**Issue by alr2413** [sadegh19b/laravel-persian-validation#2]
if you put the "1234-3523-2523-2534" as a bank card number and "ir_bank_card_number:seprate" as validation rule, it always returns false.

the same thing happens for other rules like ir_sheba, ...

**Comment by sadegh19b** [comment]
Hi @alr2413 and thanks for your points.
I'm check again validation rule you told and works fine.
This validation rule returned false because your input its wrong value.
if you want to see iranian bank card number validation algo you can visit and read [this article](http://www.aliarash.com/article/creditcart/credit-debit-cart.htm).
and about ir_sheba and others can you tell me what's wrong?

**Comment by alr2413** [comment]
i'll check now.
thanks for your quick response.

**Comment by alr2413** [comment]
I checked that, you'r right. it's working.
that was my mistake.
sorry, and thanks again. 
:)

**Comment by alr2413** [comment]
@sadegh19b 
also there is a typo in "seprate" keyword, it should be "separate".
here is a rule: "ir_bank_card_number:seprate".
thanks again.

**Comment by sadegh19b** [comment]
@alr2413 thanks for your attention.

> @sadegh19b
> also there is a typo in "seprate" keyword, it should be "separate".
> here is a rule: "ir_bank_card_number:seprate".
> thanks again.

you right, i'm incorrect write typo "seprate" and i will fixed this.
thank you anyway.
